### ISSUE TITLE
[Bug] Crash on disconnect from internet

### ISSUE THREAD

**Issue by thetakodev** [kukiteam/cfddns#2]

**Comment by Sascha-T** [comment]
Logs?

**Comment by Sanduhr32** [comment]
probably cloudflareapi throwing an exception which breaks the while loop

**Comment by thetakodev** [comment]
need to put everything inside the loop into a try-catch

**Comment by Sascha-T** [comment]
How about we actually find out what caused the problem then fix it, instead of just putting everything in the loop in a try-catch and (probably) retrying.

**Comment by thetakodev** [comment]
#3

**Comment by thetakodev** [comment]
Bug fixed. Issue closed

**Comment by thetakodev** [comment]
Issue still exists.

**Comment by thetakodev** [comment]
Fixed. Issue closed.

**Comment by Sascha-T** [comment]
It took you 2 commits, to make a try-catch clause. 2 commits. Had you given me logs it'd've taken one commit for me to properly fix the issue.

**Comment by Solly-W** [comment]
What if the numerous refrigerator ate the moon?

**Comment by Sascha-T** [comment]
There would no longer be tides.
